### ISSUE TITLE
Could not find that member.

### ISSUE THREAD

**Issue by H077y** [astridlol/Lilian#3]
After linking my pronouns page, it cannot find me. I tried both mentioning myself, and using my ID. But it can't find me.

Video: https://media.discordapp.net/attachments/638545181536419851/1077717482695045170/Screen_Recording_20230221-222250_Discord-Beta.mp4

**Comment by flowergardn** [comment]
Hey, thanks for opening an issue. I've noticed this, but I'm not so sure what's causing it. Just pushed a fix that should fix it, if you could try again?

**Comment by H077y** [comment]
Looks like it's working now! Thank you :3
Is there any way to offer up suggestions?

**Comment by flowergardn** [comment]
> Looks like it's working now! Thank you :3 Is there any way to offer up suggestions?

Apologies for the super late response, but you can either create an issue here, or join my Discord :)
